version: "2"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/db

  app:
    image: password_manager
    environment:
      - DISPLAY
    depends_on:
      - "db"
    network_mode: "host"

  
